#!/bin/bash
# This shell script takes care of starting and stopping program.
#
# chkconfig: - 90 10
# description: vanrui Tomcat for portal
# processname: tomcat-8080-portal

# Source function library.
. /etc/rc.d/init.d/functions


prog=tomcat-8080-portal
prog_web=/data/web-8080-portal
prog_keyword=tomcat-8080-portal
prog_port=8080
prog_dir=/usr/local/tomcat/tomcat-8080-portal
prog_log_dir=$prog_dir/logs
java_work_dir=$prog_dir/work

[ -d $prog_dir ] || exit 1

RETVAL=0


##########################################################################################
JAVA_HOME=/usr/local/jdk/jdk1.8.0_101
CLASSPATH=$JAVA_HOME/lib:$JAVA_HOME/jre/lib
export CATALINA_OUT=/dev/null
TLIB_OPTS="-Xbootclasspath/a:$prog_web/WEB-INF/lib/transmittable-thread-local-2.0.2.jar -javaagent:$prog_web/WEB-INF/lib/transmittable-thread-local-2.0.2.jar"
export JAVA_OPTS="$TLIB_OPTS"
##########################################################################################

if [ ! -d $JAVA_HOME ];then
	echo "JAVA_HOME Not defined";
	exit 1
fi


start() {
	prog_num=`ps ax | grep -v grep | grep java | grep "$prog_keyword" | wc -l`
	if [ $prog_num != "0" ];then
		echo $prog" already running...."
		exit 1
	fi
    
	[ -d $prog_log_dir ] || mkdir -p $prog_log_dir
	[ -d $java_work_dir ] && rm -rf $java_work_dir/*

    
	echo -n $"Starting $prog "
	nohup $prog_dir/bin/startup.sh >/dev/null 2>&1
	sleep 3s
	prog_num=`ps ax | grep -v grep | grep java | grep "$prog_keyword" | wc -l`
	if [ $prog_num != "0" ];then
		RETVAL=0
		success
		echo
	else
		RETVAL=1
		failure
		echo
	fi
 
	return $RETVAL
}



stop() {
	prog_pid=`ps ax | grep -v grep | grep java | grep "$prog_keyword" | awk '{print $1}'`
	prog_num=`ps ax | grep -v grep | grep java | grep "$prog_keyword" | wc -l`
	echo -n $"Shutting down $prog "

	if [ $prog_num = "0" ];then
		RETVAL="1"
	else
		$prog_dir/bin/shutdown.sh >/dev/null 2>&1
		sleep 3s
		prog_num=`ps ax | grep -v grep | grep java | grep "$prog_keyword" | wc -l`
		if [ $prog_num != "0" ];then
			kill -9 $prog_pid >/dev/null 2>&1
			RETVAL=$?
		else
			RETVAL=0
		fi
	fi
	
	
	if [ $RETVAL -eq 0 ];then
		[ -d $java_work_dir ] && rm -rf $java_work_dir/*
		success
		echo
	else
		failure
		echo
	fi
	
	return $RETVAL
}


status() {
	prog_pid=`ps ax | grep -v grep | grep java | grep "$prog_keyword" | awk '{print $1}'`
	prog_num=`ps ax | grep -v grep | grep java | grep "$prog_keyword" | wc -l`
	if [ $prog_num != "0" ];then
		echo "$prog (pid $prog_pid) is running..."
		return 0
	else
		echo "$prog is stopped"
		return 3
	fi
}


case "$1" in
	start)
		start
		;;
	stop)
		stop
		;;
	status)
		status
		;;
	restart)
		stop
		start
		;;
	*)
		echo "Usage: $0 {start|stop|status|restart}"
		exit 1
esac
exit $RETVAL
