#!/bin/bash
############################################
#构建中 batch操作
############################################
@echo off
xcopy /s/i/y D:\03EBA\source\SAAS\system\vanrui-user\*  %cd%
cd vanrui-user-app/
#maven操作
mvn clean package -P dev -U -Dmaven.test.skip=true

#ftp 操作start
@Echo Off
Echo open 139.129.246.118 21>C:/ftp.up
Echo root>>C:/ftp.up
Echo fhj(252019)>>C:/ftp.up
Echo cd /data/fan >>C:/ftp.up
Echo put E:\fan.txt>>C:/ftp.up
Echo bye>>C:/ftp.up
@Echo on
cd ..
ftp -s:C:/ftp.up
del C:/ftp.up /q
Pause
#ftp 操作end

############################################
#构建后 SSH操作
############################################

pro="vanrui-user-app"
pro_dir="/data/fan"

cd $pro_dir/$pro/target
unzip *.zip
cp -r $pro-*/*  $pro_dir
rm -rf $pro_dir/vanrui*

