#!/bin/bash
#operating system: CentOS  above 6



#yum install jdk-1.8


#yum install nginx



#yum install mysql



#yum install mosquitto
instMosquitto() {
	#配置yum
	
	echo "[home_oojah_mqtt]" > /etc/yum.repos.d/mosquitto.repo
	echo "name=mqtt (CentOS_CentOS-6)" >> /etc/yum.repos.d/mosquitto.repo
	echo "type=rpm-md" >> /etc/yum.repos.d/mosquitto.repo
	echo "baseurl=http://download.opensuse.org/repositories/home:/oojah:/mqtt/CentOS_CentOS-6/" >> /etc/yum.repos.d/mosquitto.repo
    echo "gpgcheck=1" >> /etc/yum.repos.d/mosquitto.repo
    echo "gpgkey=http://download.opensuse.org/repositories/home:/oojah:/mqtt/CentOS_CentOS-6//repodata/repomd.xml.key" >> /etc/yum.repos.d/mosquitto.repo
    echo "enabled=1" >> /etc/yum.repos.d/mosquitto.repo

	yum search all mosquitto
	yum install mosquitto mosquitto-clients

}
#wget download tomcat

init(){
	instMosquitto;
}

case "$1" in
	init )
		init;;
	instMosquitto)
        instMosquitto;;
		*)
        echo "Usage: $0 {init|instMosquitto|status|restart}"
            exit 1
esac
exit 0